name: Build and Publish Release Artifacts

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build ${{matrix.os}}-${{matrix.arch}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.4.0

    - name: Test
      run: go test -v ./...

    - run: mkdir roadmap-${{matrix.os}}-${{matrix.arch}} && env GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -o roadmap-${{matrix.os}}-${{matrix.arch}} ./... && zip -r roadmap-${{matrix.os}}-${{matrix.arch}}.zip roadmap-${{matrix.os}}-${{matrix.arch}}

    - name: Upload ${{matrix.os}}-${{matrix.arch}} Release Asset
      uses: SierraSoftworks/gh-releases@v1.0.7
      with:
          files: roadmap-${{matrix.os}}-${{matrix.arch}}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: "true"
