name: Build and Publish Release Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.17.0

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.0.2

    - run: env GOOS=linux GOARCH=amd64 go build -o roadmap-graphviz-linux-amd64 ./...
    - run: env GOOS=windows GOARCH=amd64 go build -o roadmap-graphviz-windows-amd64 ./...

    - name: Test
      run: go test -v ./...

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: v${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: roadmap-graphviz-linux-amd64
        asset_path: ./roadmap-graphviz-linux-amd64
        asset_content_type: application/binary-x

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: roadmap-graphviz-windows-amd64
        asset_path: ./roadmap-graphviz-windows-amd64
        asset_content_type: application/binary-x
